name: Build rtl_433 images

on:
  push:
    branches:
      - next
      - main
  pull_request:

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_rtl_433:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --docker-hub ghcr.io \
          --image tjcav/rtl_433-hass-addons-rtl_433-{arch} \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433

  build_rtl_433_mqtt_autodiscovery:
    name: Build rtl_433_mqtt_autodiscovery addon
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --docker-hub ghcr.io \
          --image tjcav/rtl_433-hass-addons-rtl_433_mqtt_autodiscovery-{arch} \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target rtl_433_mqtt_autodiscovery
